### ISSUE TITLE
 lftools.mlib is readonly

### ISSUE THREAD

**Issue by hhsievertsen** [sergiocorreia/reghdfe#107]
Hi Sergio,
thanks for an excellent command. 

After the latest updates we have had a lot of issues with reghdfe. Lately we get the message " lftools.mlib is readonly" (for example after "sysuse auto reghdfe price weight, absorb(rep78)"). Do you have any idea why? 

Our challenge is that we are running Stata on a server with no internet access, and no admin rights for any of the users. We cannot just update packages :-/.

**Comment by sergiocorreia** [comment]
Do you have ftools installed? (The new reghdfe requires ftools.)

If so, can you type the following:

ftools, version
ftools, compile

**Comment by sergiocorreia** [comment]
Hi Hans,

I noticed that if for some reason someone set ftools.mlib as read only, you'll be in trouble.

Since sysadmins might make the sysdir_plus directory read-only, the version of ftools I just pushed does two things as workarounds:

- Detects read-only errors
- In case of a read-only error, it will try to write into another folder: first we try in sysdir_plus, then in sysdir_personal, and then in the current working folder.

This is not guaranteed to work for every corner case, but should make things easier on your side. Let me know how it works.

**Comment by hhsievertsen** [comment]
Hi Sergio, 
thank for the quick response. 

First, `ftools,version `doesn't work for me (says ftools has no version option), however `reghdfe, version` says everything is fine (reghdfe version form June, ftools installed). ftools, `compile fails `(readonly error). 

Second, your solution works for me on my local computer. I just asked our sysadmin to update ftools on the server. 

Thanks a lot!

**Comment by sergiocorreia** [comment]
Yep, I forgot that it was reghdfe that has `,version` (you can use `which ftools` to see what version of ftools do you have).

By the way, If possible also tell your sysadmin to delete existing versions of lftools.mlib

**Comment by benjaminhyman** [comment]
Hi Sergio, just wanted to add a note as a public good for any other Census RDC researchers (who have told me more than once that they've gotten the same errors and found your responses to my questions on these threads which resolved them!)

The latest (Feb '23): Census admins will update Stata version but lock the supporting depedencies as read-only. As Sergio notes above, you have to recompile ftools (and reghdfe) to get get the Stata-16 specific files, prioritizing the appropriate adopath++. 

Thanks as always Sergio, for all this great documentation!
