### ISSUE TITLE
Dropping due to collinearity when using aweights

### ISSUE THREAD

**Issue by heidenfahrt** [sergiocorreia/reghdfe#109]
I am currently facing a case where running `reghdfe` without weights works fine and yields the same result as `reg` with dummies. When I specify for example `[aweight = population]`, it drops several variables due to collinearity, while `reg` does not show this behavior. Regressing one of the dropped variables on all other explanatory variables leads to an R-squared smaller than 1.

**Comment by sergiocorreia** [comment]
Do you have a [MWE](https://en.m.wikipedia.org/wiki/Minimal_Working_Example) by any chance?

**Comment by heidenfahrt** [comment]
I'm currently trying to create one which is not too easy as the dataset is of course a little peculiar. I'll report back.

**Comment by heidenfahrt** [comment]
Here is an example of the decribed behavior:
```
use "https://www.dropbox.com/s/mjm793n9dwnq6bp/mwe.dta?dl=1", clear

// Regression without weights
// regress
reg y treat control1-control14
// reghdfe
reghdfe y treat control1-control14, noabs 


// Regression with weights
// regress
reg y treat control1-control14 [aweight=population]
// reghdfe
reghdfe y treat control1-control14 [aweight=population], noabs 
```
Where in the last command the described behavior is observed.

**Comment by sergiocorreia** [comment]
I just uploaded a commit that fixes this (check that your version is 4.3.9).

Now, to explain a bit *why* this happens.

First, the dataset has some serious collinearity problems. If we run `estat vif` after regress, we get this:

```stata
. estat vif

    Variable |       VIF       1/VIF  
-------------+----------------------
    control7 |   5939.48    0.000168
   control13 |   5604.93    0.000178
    control1 |    345.97    0.002890
   control14 |    130.69    0.007651
    control5 |     93.10    0.010741
    control8 |     50.65    0.019742
    control6 |     38.40    0.026040
    control2 |     33.25    0.030072
   control10 |     29.02    0.034458
   control12 |     24.32    0.041120
    control3 |     11.17    0.089559
   control11 |      8.31    0.120309
    control4 |      3.23    0.309666
    control9 |      3.19    0.313193
-------------+----------------------
    Mean VIF |    879.69
```

In general, a VIF above 10 is considered to be a [problem](https://en.wikipedia.org/wiki/Variance_inflation_factor), and VIFs around 5,000 make computing `inv(X'X)` quite difficult.

Second, the code that I just [replaced](https://github.com/sergiocorreia/reghdfe/commit/d5ca3cb07be87cc2725b652d2a287b605af79811) was doing `qrsolve(XX, XY)` in cases with weights, and `qrsolve(X, y)` in cases without weights (the XX matrices used by cholsolve were computed as `cross(X, weight, X)`, but there is no such option in qrsolve.

As discussed [here](http://www.stata.com/statalist/archive/2012-02/msg00956.html) those two options should give you the same results, but qrsolve is more numerically accurate, which matters in your case because your XX matrix is almost singular.

Thus, in your particular case the combination of both approximate collinearity and weights made the computation of `b` inaccurate. The new version should give results like `regress`, but I would still recommend inspecting the covariates to remove suspicious regressors (such as control7 and control13; if you run `reg control7 control13 [aweight=population]` you'll get an R2 of 1.000)

**Comment by heidenfahrt** [comment]
Thanks a lot for the fix Sergio!
Actually, control13 is the square of control7. As control7 is a number in the 1000s with small variance, the square is just very large. 
Do you actually have some experience / would you recommend to scale down large-valued variables to improve performance?

**Comment by sergiocorreia** [comment]
It never hurts to rescale. Most programs do that by default but there might be some corner cases.

More importantly, control13 is stored as a `float`, which might be the reason behind the problems. I would suggest recreating it as a double from the start (and in general, keeping everything as either doubles or integer types, as floats lead to these errors).

Best,
Sergio
