### ISSUE TITLE
Possible bug handling variables with very large numbers

### ISSUE THREAD

**Issue by dgcbritto** [sergiocorreia/reghdfe#151]
Hi,
I've been running regressions while controlling for high order polynomials on wage. When the order was too high (from the fourth), reghdfe sets some of the coefficient to zero. The same does not happen with areg. I rerun the regressions after scaling down the polynomial controls by a constant factor and the regression goes through.

To see the issue, you can run the code:
clear
set seed 123
set obs 10000
g y = _n*100 + uniform()*100
g x = _n*100
g fe = int(_n/10)

// some coefficients wrongly set to zero
reghdfe y c.x##c.x##c.x##c.x##c.x##c.x, absorb(fe)
// areg regression goes through ok
areg y c.x##c.x##c.x##c.x##c.x##c.x, absorb(fe)
// scaling down the variable solves the issue
replace x = x/10^6
reghdfe y c.x##c.x##c.x##c.x##c.x##c.x, absorb(fe)

**Comment by sergiocorreia** [comment]
An iterative method, like reghdfe, will always have lower numerical accuracy than a direct method (like areg). Just for one reference, check [here](https://epubs.siam.org/doi/abs/10.1137/1.9780898718027.ch17): 

> rounding error analysis for iterative methods is inherently more difficult than for direct methods, and the bounds that are obtained are harder to interpret.

In this case, even though you only run one iteration (because you only have one fixed effect), it seems that the fact that this is almost a degenerate case (the R2 is .99999999) makes it very hard for reghdfe to get the exact same solution.

What surprised me is that rescaling fixes the problem. reghdfe internally rescales (to prevent this kind of issues), but only rescales the final x^2 variables and not the original x variable, so that might be the issue. I dug a bit but can't find any clear answers on why this happens, besides the fact that it's not an obvious bug in the code.

**Comment by dgcbritto** [comment]
I see, thanks for pointing this out Sergio.
This issue bugged me for a while and I couldn't understand why some coefficients were not being estimated. I've thought about sharing it and the solution that worked for me as others may face similar issues.

Feel free to close the issue!

**Comment by dgcbritto** [comment]
Ok!

________________________________
De: Sergio Correia <notifications@github.com>
Enviado: quarta-feira, 17 de outubro de 2018 13:04
Para: sergiocorreia/reghdfe
Cc: dgcbritto; Author
Assunto: Re: [sergiocorreia/reghdfe] Possible bug handling variables with very large numbers (#151)


Ill leave it open, so it's easier for others to spot it (and one day I might find a way to ameliorate the problem)
