### ISSUE TITLE
Predict outside e(sample)

### ISSUE THREAD

**Issue by matthieugomez** [sergiocorreia/reghdfe#17]
Is there an option in `predict` to compute predicted value outside `e(sample)`, as in `reg`? 

```
sysuse nlsw88, clear

* reg: predict generates predicted values for all observations
reg wage i.race if married == 0
predict temp1
assert temp1 <.

* reghdfe:  predict generates predicted values only for observations in e(sample)
reghdfe wage if married == 0, a(race, savefe)
predict temp2, xbd
assert temp2 <.
```

A typical case is to compute fixed effects using only observations with treatment = 0 and compute predicted value for observations with treatment = 1.

**Comment by sergiocorreia** [comment]
Would it make sense if you are able to only predict the -xb- part?
This has been discussed in the past in the context of -areg- and the idea was that outside the sample you don't know the fixed effects outside the sample

**Comment by sergiocorreia** [comment]
To extend:

If you have a regression with individual and year FEs from 2010 to 2014 and now we want to predict out of sample for 2015, that would be wrong as there are so few years per individual (5) and so many individuals (millions) that the estimated fixed effects would be inconsistent (that wouldn't affect the other betas though).

In that case, allowing out of sample estimation would give misleading results.

Another case is to add additional individuals during the same years. The estimates for the year FEs would be consistent, but another question arises: what do we input instead of the FE estimate for those individuals. 0?

**Comment by matthieugomez** [comment]
No I'd like to predict the whole part. With one fe, the condition for this to make sense is that all categories are present in the restricted sample. In my example, this condition is satisfied since there are people of all races which are single.

Another user case is to fit individual specific trend using only data before a treatment. Although of course, it does not make sense to compute predictions for individuals that are always treated.

Now I'm unsure what the condition is with multiple fixed effects. Would you know it?

**Comment by sergiocorreia** [comment]
Note that a workaround can be done if you save the fixed effects and then replace them to the out-of-sample individuals.. something like

```stata
reghdfe ... absorb(FE1=id1 FE2=id2) ...

bys id1 (FE1): replace FE1 = FE1[1]
replace FE1 = 0 if FE1 = .

bys id2 (FE2): replace FE2 = FE2[1]
replace FE2 = 0 if FE2 = .

gen d = id1 + id2
predict xb, xb
gen xbd = xb + d
```

The two replace lines are also interesting as they relate to the two problems discussed above:

1. How to deal with new individuals--set them as 0--
2. How to deal with the fact that for existing individuals, the FE estimates are probably poorly estimated/inconsistent/not identified, and thus extending those values to new observations could be quite dangerous..
