### ISSUE TITLE
Inferior parameterization of  i.x##c.z

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sergiocorreia/reghdfe#22]
Let covariate `x` be binary.

Compare:

``` stata
areg y i.x##c.z, a(fe)
reghdfe y i.x##c.z, a(fe)
```

`areg` parameterizes the covariates as (1) `1.x`, (2) `c.z`, and (3) `1.x#c.z`.

`reghdfe` parameterizes the covariates as (1) `1.x`, (2) `c.z`, (3) `0.x#c.z`, and (4) `1.x#c.z`. Then (4) is omitted for collinearity.

I prefer `areg` here.

Might be related to bda7e038.

I'm using reghdfe 3.0.10 13may2015.

**Comment by sergiocorreia** [comment]
I agree with you that the -areg- way is cleaner.

That said, the fix is not that simple:

```stata
sysuse auto
local 0 foreign##c.weight
syntax varlist(fv)
di "`varlist'"
```

As you can see, `syntax` expands the ## interaction so when I call `fvrevar` it's already expanded, and `fvrevar` needs it together in order to tag the `0.x#c.z` element as omitted.

I checked the `areg` code and they use `syntax anything` instead of `syntax varlist(fv)` and then let `_regress` handle the factor variables, which is not an option for me.

Will think if there is a sane workaround...

**Comment by sergiocorreia** [comment]
(update)

I thought about maybe replacing the "##" with a "#" and then adding it back after syntax. However, that workaround doesn't work well in complex cases (e.g. x1#c.z1##c.z2#x2) so I'm not very enthusiastic about it. I'll leave the issue open until a better solution is found.

**Comment by NilsEnevoldsen** [comment]
I just discovered the workaround `reghdfe y 1.x##c.z, a(fe)`.

**Comment by sergiocorreia** [comment]
Closing and tagging as *wontfix* so I can't search for it in the future (but it's more like *cantfix*)

**Comment by sergiocorreia** [comment]
Works on dev release
