### ISSUE TITLE
Question on "VCV matrix was non-positive semi-definite; adjustment from Cameron, Gelbach & Miller applied."

### ISSUE THREAD

**Issue by leonschmidt93** [sergiocorreia/reghdfe#221]
Hello Sergio,

Thank you very much for the great work with reghdfe!

I have one question. Sometimes, even though all F and p statistics and standard errors are calculated, I get the warning "VCV matrix was non-positive semi-definite; adjustment from Cameron, Gelbach & Miller applied." Is this problematic? Or is this non-problematic because there is an adjustment applied?

Thank you very much for your help!

All the best
Leon

**Comment by leonschmidt93** [comment]
Further discussed here https://www.statalist.org/forums/forum/general-stata-discussion/general/1591280-regdhfe-and-warning-adjustment-from-cameron-gelbach-miller-applied

**Comment by sergiocorreia** [comment]
Hi Leon,

It's not problematic, because it's adjusted following the Cameron et al approach. That said, it usually means that you are a bit far from the asymptotics assumed by Cameron et al, so it would be good to double check that you have enough clusters (what is enough is never clear of course, besides their rule of thumb of ~50 clusters).

**Comment by leonschmidt93** [comment]
Thank you very much for your answer Sergio, feels good to be on the safe side!
