### ISSUE TITLE
var1#var2 in the absorb

### ISSUE THREAD

**Issue by nepse** [sergiocorreia/reghdfe#23]
Consider following four examples:
`sysuse auto,clear`

**a.** `reghdfe price turn,absorb(rep78 foreign rep78#foreign)`
`variable rep78 not found`
`r(111);`

**b.** `reghdfe price turn,absorb(rep78#foreign rep78 foreign)`
runs without error 

**c.** `qui gen price1=price>6100`
 `reghdfe price turn,absorb(price1 rep78#foreign)`
runs without error 

**d.**  `reghdfe price turn,absorb(price1 rep78 rep78#foreign)`
`variable rep78 not found`
`r(111);`

I was wondering whether this means we should always include `var1#var2` at the beginning when we are also including either `var1` or `var2` or both ? Is this the default behavior? I am using `reghdfe 2.1.10 07apr2015`.

**Comment by sergiocorreia** [comment]
Hi nepse,

Agree with you that it's a bit confusing.

- The original idea of raising errors was that in those cases there was probably something wrong/inefficient in your command. For instance, on a) there is not much to gain from having both rep and rep#foreign instead of just rep#foreign . This also applies for d), although not for b)
- However, this was not always the case and thus became problematic. Therefore, this has been fixed starting with reghdfe 3.x

The instructions for 3.x are similar to those for 2.x, they are in the main README file. Note that some advanced options have a different syntax now (stages, cache). Let me know if you find any bugs with it (major bugs should be caught by the test suite, but corner cases while parsing are harder to spot)

**Comment by nepse** [comment]
Thank you for the response. I just installed the new version, and it works perfect. Thank you also for the great package.

**Comment by sergiocorreia** [comment]
Great to hear that, and glad it's useful for you!
S
