### ISSUE TITLE
Slope-only models

### ISSUE THREAD

**Issue by matthieugomez** [sergiocorreia/reghdfe#33]
I don't really get what reghdfe does in the case of only one interaction.

```
sysuse nlsw88.dta
reghdfe wage, a(fe = c.tenure#i.grade) keepsingletons
```
The resulting variable fe_Slope1 differs from
```
reg wage c.tenure#i.grade, nocons
```

Also,  `predict y` returns a variable equal to zero

**Comment by sergiocorreia** [comment]
There may be a couple of bugs around that. One in the R2, one with the FEs, and another in predict.

I'll try to tackle them tonight, and also add a test suite.

Best,
S

PS: Are you aware of any kaczmarz solver for Stata? R's *lfe* extracts the alphas (the FEs) with a Kaczmarz solver, but I'm doing it the long way (with the same solver used to perform the demeanings), which saves me coding time but is slower.

**Comment by sergiocorreia** [comment]
Found the bugs. The ones regarding e() were mostly minor but the wrong alphas are important enough to push it into SSC asap.

About -predict-, I think zeros is the correct result.
If you want to include the fixed effects in the prediction, the option is "xbd" (instead of "xb", the default).

Best,
S

**Comment by matthieugomez** [comment]
Thanks a lot ! This kind of specification is useful to estimate unbalanced factor models (the idea is to alternatively do
```
reghdfe  y, a(fetime = c.feid_Slope#i.time)
reghdfe y, a(feid = c.fetime_Slope#i.id)
```
until convergence

I don't know anything about kaczmarz solver for Stata, but I don't really know about optimizers  in Stata to begin with.  It's funny you asked, I just [coded a Julia version](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/src/getfe.jl) this we.

**Comment by sergiocorreia** [comment]
That code looks really cool! Writing a getfe mata function has been in my to-do list for a while, but I won't tackle it until after the JM (right now the equivalent function works but it's quite slow).

About the unbalanced factor models, do you have any reference I could check out? (is it related to the Bai model?)

Also, are you only using one factor in absorb() each time, or many? Because if it's only one, it would be faster to use the resid() option and then obtain the FE by substraction (y - resid - mean(y)). I also heard about a [peer effect model](http://onlinelibrary.wiley.com/doi/10.3982/QE145/abstract) that can be solved by iterating reghdfe calls until convergence. If the need for iterations like this is common, maybe exposing the internals directly woul be interesting.

**Comment by matthieugomez** [comment]
It corresponds to the method called EM algorithm in this paper: http://users.ics.aalto.fi/juha/papers/pca_iconip07.pdf 
(regife currently uses what they call "Adapting SVD algorithm")
I'm still not sure it's the fastest/more robust method yet, but it seems to work well in my trials and it's more intuitive than a SVD (i.e. this is just regressions).
Maybe you'll find this readme interesting: https://github.com/matthieugomez/SparseFactorModels.jl

**Comment by matthieugomez** [comment]
Contrary to what the article implies, the algorithm only needs to estimate y = beta_i x (with only one regressor) within groups, and so a simple running sum of yx and x^2 within each group is enough.
The relevant code in Julia is here : [here](https://github.com/matthieugomez/SparseFactorModels.jl/blob/4166ebea01764d8f0d3cfb6634333ea638f3cfd0/src/update!.jl#L19)
