### ISSUE TITLE
The link to download the zip file from the website seems to be broken.

### ISSUE THREAD

**Issue by achenzion** [sergiocorreia/reghdfe#36]

**Comment by sergiocorreia** [comment]
Hi Ayal,

You are right. I stopped posting the zip files because since they are binary files they were not playing well with Github (git prefers text files, and diff-able files).

The main reason why I kept the zipfiles was for users of Stata 12 (that cannot access https). Since I now keep a copy of the package files on `net install reghdfe, from(http://scorreia.com/stata/reghdfe)`, I didn't think this was necessary.

If you need to copy the package to a server without internet, you can download the project ( https://github.com/sergiocorreia/reghdfe/archive/master.zip ) and navigate to the *package* folder.

More generally, do you think it might be useful to add back the zip files? I can add them as "package releases" to github or as simple zipfiles to my server.

Best,
Sergio

**Comment by achenzion** [comment]
You picked out my problem exactly. The server I am working on does not have internet. I think that this situation would be the main use case for the zip file. I am not sure how many people this impacts, but at a minimum I would take down the broken links.

Thank you so much for all of your hard work on this package. It is really great!

Cheers,

Ayal

**Comment by sergiocorreia** [comment]
You are welcome! I'll add the zip files (as well as the help file and user guide) as soon as I finish with the JMP draft.. see you at the ASSA!

Sergio
