### ISSUE TITLE
Large Data Set - Issue?

### ISSUE THREAD

**Issue by Nathan742** [sergiocorreia/reghdfe#50]
Hi,

I am new to using reghdfe and have encountered what I believe to be an issue. I have a large dataset (40+gb) and am trying to run a regression with 2 fixed effects. The first time I ran the regression i received the following errors:
 
reghdfe lnkwh treatment_event*, absorb(date_time customer_id) vce(robust)
(dropped 182 singleton observations)

        map_projection():  3900  unable to allocate real <tmp>[195026781,10]
transform_sym_kaczmarz():     -  function returned error
         accelerate_cg():     -  function returned error
             map_solve():     -  function returned error
                 <istmt>:     -  function returned error
r(3900);

I then changed my code so that I had pool(3) since I had read that this used less memory. I am running Stata 12.0 on a server and have a maximum memory of 256gb available. When I tried re-running it, the regression then got a bit further but still isn't quite working. I'm not getting any output and there are no estimates to store. I know this code works when I run it on a much smaller sample (2gb of the data). For reference date_time will contain about 42,000 fixed effects and customer_id has 7,500 fixed effects.

reghdfe lnkwh treatment_event*, absorb(date_time customer_id) vce(cluster customer_id) cache(save) pool(3)
(dropped 182 singleton observations)
(converged in 7 iterations)

. 
. estimates store Load_Shifting
last estimation results not found, nothing to store
r(301);

Any tips/ideas on what I might need to try differently?

**Comment by sergiocorreia** [comment]
Hi Nathan!

Two things are going on here:

1) I've also had troubles trying to allocate a lot of memory with Stata 12.1 on a Linux server.

I don't recall exactly if it was due to the "serious bug on Linux" (see http://www.stata.com/manuals13/dmemory.pdf )  or if this was related to user allocation limits (like here: http://www.stata.com/statalist/archive/2005-12/msg00357.html ) but it's independent of reghdfe (and I guess that Stata Tech support could give you more clues about that, as they are fairly responsive!)

That's why using a smaller `pool(#)` helps, as it makes reghdfe use less memory, although at the cost of speed (not much difference though). Just to be safe, you can use pool(1).

2) If you use the `cache(save)` option you actually never ran the regression, just precomputed the transformed variables, so there are no estimates to store.

You can see an example of how use cache(save) and cache(use) together here:
http://scorreia.com/software/reghdfe/faq.html#i-want-to-repeat-a-regression-with-different-outcome-variables-can-i-compute-the-transformations-only-once

Cheers,
S

**Comment by Nathan742** [comment]
Hi Sergio!

Thanks for your quick reply. I will retry with the correct usage of cache and let you know how it goes.

Cheers,
Nathan

**Comment by Nathan742** [comment]
When I use pool(1) I can use reghdfe on my large data without any issues. Thanks!
