### ISSUE TITLE
residuals - predict ue instead of e

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#66]
In order to perform the Born & Breitung (2016) Q(p) test for serial correlation in a fixed effect setting, currently en route to ssc as xtqptest, the "ue" residuals are required, i.e. c_i + e_it. Currently, I believe the only way to obtain these after reghdfe is to use the residuals option and save the fixed effect separately, afterwards adding them up.

It would be great if this were possible in one step, e.g. residuals(newvarname, ue).

Edit: It's currently not possible to predict the residuals and save the fixed effects.

**Comment by sergiocorreia** [comment]
I'm not sure of how to decide what "c_i" would be included

For instance, suppose we do something like `reghdfe wage experience, absorb(worker firm year)`. Does `c_i` refer to the worker FEs, the firm FEs, etc.? (this is trivial in an `xtreg` command because there is only one level of fixed effects)

Another detail is that in order to generate fixed effect estimates, we use some intermediate variables, that's why we save the FEs at the time of the estimation and not later with a `predict` command.

**Comment by Danferno** [comment]
The c_i would refer to the unit used in the regression. As in, if each line represents one worker, the c_i would refer to workers. This would be the variable returned as r(panelvar) by xtset. 

That said, it's not a crucial addition (few people actually need the ue residuals).

**Comment by sergiocorreia** [comment]
I see... I'll mark it as -wontfix- as I still see a few complications (but feel free to reopen it or post further suggestions on the issue)

Some of the complications are:

- What if the absorb variable doesn't match the r(panelvar) variable (with xtreg they always match)
- What if the user didn't save the FEs so he can't save the results (so in any case we can't always predict "ue")

Additionally, it's not that complicated to save the FE and add it to the residual (less pressing than some of the other current issues)
