### ISSUE TITLE
problem with slopes (was: "reghdfe")

### ISSUE THREAD

**Issue by aggraz** [sergiocorreia/reghdfe#71]
Hi Sergio,

I am using reghdfe to estimate an equation with exporter-importer fixed effects and exporter and importer specifics linear time-trends. One of the specific time-trends should be dropped because it's collinear, but the command doesn't do it and instead reports huge standard errors on all the time-trends (not on the variable I am interested in).  Also, the K-1 degrees of freedom in the F-stat is wrong in this case (many less). When I manually drop one time-trend, both the standard errors and the DoF are ok. 

Would you help me to understand what is happening?

Thanks!
Alejandro

**Comment by sergiocorreia** [comment]
Could you share a minimum-working-example (MWE) of the problem (perhaps privately if you want) in order to debug the problem? Also, one question, are you absorbing with something like `exporter##time` or with `exporter exporter#time`? (the first has better numerical properties)

I think one of two things might be at play:

- Since reghdfe is an iterative method, there is always some residual left after demeaning. Stata has a routine that detects when it's "close enough to zero" to drop it, but it doesn't work that well for our specific purposes. A quick fix might be to use a more strict tolerance (see the option `tolerance`, or add the option `tol(1e-10)` in your code). A more robust fix would be to adapt Stata's routine to deal with variables that are very close to zero but not that much as Stata expects.
- The second alternative lies in the standard errors of time trends. I recall that numerical errors are higher when absorbing trends, but I was never sure if this was due to an implementation problem or just because of the nature of the estimation. In fact, I think this issue is in one of the still-open bug reports. In this case, if you have a MWE that would be super useful to find the bug.

The DoF problem is probably also related, because the Stata command that detects collinear variables also computes K-1.

Best,
S

**Comment by aggraz** [comment]
Thank you for your answer Sergio.

I am actually constructing the interactions by myself because it's being
much less demanding in terms of memory. Given that I am absorbing
exporter-importer fixed effect, I only need the exporter#time and
importer#time (the exporter and importer fixed effects are captured by the
exporter-importer fixed effect it's being absorbed).

It seems a numerical problem, but I tried by relaxing the tolerance and
it's not changing the outcome. I don't think it's related to a problem with
the trends per se because I don't get the huge standard errors once I drop
one trend (solving the collinearity).

I'll send you a private message with a MWE.

Thanks,
Alejandro

**Comment by sergiocorreia** [comment]
This should have been fixed in the new version (if not, feel free to open the bug and let me know)
