### ISSUE TITLE
invalid options: nested

### ISSUE THREAD

**Issue by xorg123** [sergiocorreia/reghdfe#74]
When using the command (the dev or the ssc version) like this `reghdfe depvar indvar, absorb(fe1 fe2 fe3, save) nested` I receive the following error: 

> invalid options: nested

Using verbose does not give much more insight on what is going on

However, when using the exact same syntax with `reghdfe_old` instead everything seems to work just fine.

**Comment by sergiocorreia** [comment]
Yep, I need to update the help file.

I removed the `nested` option a while ago. Since these tests are only valid with vanilla standard errors (and at this point most people cluster or do something similar), they are not very useful, but the code behind them was cumbersome.

In any case, you can replicate them by hand relatively easily, as it's just the standard Ftest based on R2s or sum of squared residuals.

Best,
S

PS: If you have any suggestions for what to run instead, let me know (maybe there are new papers that give a robust way to test this)

**Comment by xorg123** [comment]
Thank you for your quick reply. 

Long story short, I was using `felsdvreg` for a prior paper (with much less observations naturally) with robust errors and I thought it was convenient for discussion purposes to get the f-tests and the proportion explained covariance by the fixed effects. 

Is there a way with `reghdfe` to have a clue of the "relative importance" of the fixed effects? (The increase in R-squared is nothing more then a mechanical result of increasing the number of "indvar" in the model I think).

**Comment by sergiocorreia** [comment]
I'm not aware of a clean way to do so.

One alternative is to use the adjusted R2, as it's less mechanic than the reported R2 (you can view it with `ereturn list`).

Another would be to see if adding FEs makes a difference in the estimates of the main regressors but I'm not sure if it's that useful (if adding another layer of FEs makes a difference, it might be because the extra layer matters, or because the extra layer absorbed so much information that the errors are now too noisy)

**Comment by sergiocorreia** [comment]
By the way, perhaps Bai says something about it?

http://onlinelibrary.wiley.com/doi/10.3982/ECTA6135/abstract

From the abtract it seems he shows a way to test additive vs interactive FEs, so maybe there's something useful for your case (I can't access the paper until tomorrow)

**Comment by xorg123** [comment]
Thank you. Interesting indeed.

By the way, Bai made a MatLab program (seems to work in GNU Octave 4.0.3 on
my side) for this paper, you might want to have a look.

http://fmwww.bc.edu/repec/bocode/i/interactivefixedeffects.zip

2016-09-14 14:51 GMT+10:00 Sergio Correia <notifications@github.com>:

**Comment by sergiocorreia** [comment]
I haven't checked it, but if by any chance you want to run this in Stata, [regife](https://github.com/matthieugomez/regife.ado) by Matthieu Gomez is a very good implementation (I think it used a better algorithm that Bai)

**Comment by sergiocorreia** [comment]
Fixed
